# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\peter\Desktop\Programming\GitHub\Python-Web-Crawler\Pastpaper-Downloader-GUI\pastpaper_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(531, 799)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 481, 771))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(True)
        self.label.setTabletTracking(False)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pre_folder = QtWidgets.QToolButton(self.splitter)
        self.pre_folder.setObjectName("pre_folder")
        self.open = QtWidgets.QToolButton(self.splitter)
        self.open.setObjectName("open")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.splitter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.display_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.display_line.setReadOnly(True)
        self.display_line.setObjectName("display_line")
        self.gridLayout_2.addWidget(self.display_line, 0, 1, 1, 1)
        self.mutichoose = QtWidgets.QToolButton(self.layoutWidget)
        self.mutichoose.setObjectName("mutichoose")
        self.gridLayout_2.addWidget(self.mutichoose, 0, 3, 1, 1)
        self.current_folder = QtWidgets.QLabel(self.layoutWidget)
        self.current_folder.setObjectName("current_folder")
        self.gridLayout_2.addWidget(self.current_folder, 0, 0, 1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.info = QtWidgets.QTableView(self.layoutWidget)
        self.info.setEnabled(True)
        self.info.setObjectName("info")
        self.horizontalLayout.addWidget(self.info)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.download = QtWidgets.QPushButton(self.layoutWidget)
        self.download.setObjectName("download")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.download)
        self.store_place = QtWidgets.QPushButton(self.layoutWidget)
        self.store_place.setObjectName("store_place")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.store_place)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PastPaper_Downloader"))
        self.label.setText(_translate("MainWindow", "Pastpaper 下载器"))
        self.pre_folder.setText(_translate("MainWindow", "上一级文件夹"))
        self.open.setText(_translate("MainWindow", "打开文件夹"))
        self.display_line.setText(_translate("MainWindow", "Home"))
        self.mutichoose.setText(_translate("MainWindow", "多选功能"))
        self.current_folder.setText(_translate("MainWindow", "当前文件夹"))
        self.download.setText(_translate("MainWindow", "下载所选文件 Ctrl+D"))
        self.store_place.setText(_translate("MainWindow", "文件储存位置"))
